# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("defcdb", "0014_auto_20151207_1003"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="area",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="area",
            name="created_with_session_key",
        ),
        migrations.RemoveField(
            model_name="area",
            name="modified_by",
        ),
        migrations.RemoveField(
            model_name="area",
            name="modified_with_session_key",
        ),
        migrations.RemoveField(
            model_name="finds",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="finds",
            name="created_with_session_key",
        ),
        migrations.RemoveField(
            model_name="finds",
            name="modified_by",
        ),
        migrations.RemoveField(
            model_name="finds",
            name="modified_with_session_key",
        ),
        migrations.RemoveField(
            model_name="interpretation",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="interpretation",
            name="created_with_session_key",
        ),
        migrations.RemoveField(
            model_name="interpretation",
            name="modified_by",
        ),
        migrations.RemoveField(
            model_name="interpretation",
            name="modified_with_session_key",
        ),
        migrations.RemoveField(
            model_name="name",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="name",
            name="created_with_session_key",
        ),
        migrations.RemoveField(
            model_name="name",
            name="modified_by",
        ),
        migrations.RemoveField(
            model_name="name",
            name="modified_with_session_key",
        ),
        migrations.RemoveField(
            model_name="period",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="period",
            name="created_with_session_key",
        ),
        migrations.RemoveField(
            model_name="period",
            name="modified_by",
        ),
        migrations.RemoveField(
            model_name="period",
            name="modified_with_session_key",
        ),
        migrations.RemoveField(
            model_name="reference",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="reference",
            name="created_with_session_key",
        ),
        migrations.RemoveField(
            model_name="reference",
            name="modified_by",
        ),
        migrations.RemoveField(
            model_name="reference",
            name="modified_with_session_key",
        ),
        migrations.RemoveField(
            model_name="researchevent",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="researchevent",
            name="created_with_session_key",
        ),
        migrations.RemoveField(
            model_name="researchevent",
            name="modified_by",
        ),
        migrations.RemoveField(
            model_name="researchevent",
            name="modified_with_session_key",
        ),
        migrations.RemoveField(
            model_name="site",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="site",
            name="created_with_session_key",
        ),
        migrations.RemoveField(
            model_name="site",
            name="modified_by",
        ),
        migrations.RemoveField(
            model_name="site",
            name="modified_with_session_key",
        ),
    ]
