# Generated by Django 4.2.7 on 2023-11-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        help_text="In format 'year-month-day', e.g. 2016-04-24",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="In format 'year-month-day', e.g. 2016-04-24",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=500, null=True)),
                ("place", models.CharField(blank=True, max_length=200, null=True)),
                ("webpage", models.URLField(blank=True, null=True)),
                ("comment", models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                "ordering": ("-start_date",),
            },
        ),
    ]
