# Generated by Django 4.2.7 on 2023-11-07 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("defcdb", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=500, null=True)),
                ("last_name", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "institution",
                    models.ManyToManyField(
                        blank=True, to="defcdb.dc_researchevent_institution"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inclusion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inclusion_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "inclusion_type",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "inclusion_color",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "inclusion_form",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "inclusion_particle_size",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "inclusion_frequency",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "inclusion_hardness",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=500, null=True)),
                ("title", models.CharField(blank=True, max_length=500, null=True)),
                ("source", models.CharField(blank=True, max_length=500, null=True)),
                ("language", models.CharField(blank=True, max_length=500, null=True)),
                ("keywords", models.CharField(blank=True, max_length=500, null=True)),
                ("publisher", models.CharField(blank=True, max_length=500, null=True)),
                ("issued", models.CharField(blank=True, max_length=500, null=True)),
                ("license", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "access_rights",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "contact",
                    models.ManyToManyField(blank=True, to="threedmodels.contact"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Threedmodel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_id", models.CharField(blank=True, max_length=100, null=True)),
                ("part", models.CharField(blank=True, max_length=500, null=True)),
                ("diameter", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "wall_thickness",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "surface_treatment_i",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "surface_treatment_o",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "surface_color_i",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "surface_color_o",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "decoration_color",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "decoration_description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "fabric_color",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("hardness", models.CharField(blank=True, max_length=500, null=True)),
                ("sorting", models.CharField(blank=True, max_length=500, null=True)),
                ("density", models.CharField(blank=True, max_length=500, null=True)),
                ("pores", models.CharField(blank=True, max_length=500, null=True)),
                ("core_form", models.CharField(blank=True, max_length=500, null=True)),
                ("core_color", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "model_file",
                    models.FileField(blank=True, null=True, upload_to="models"),
                ),
                (
                    "model_thumbnail",
                    models.FileField(blank=True, null=True, upload_to="thumbnails"),
                ),
                (
                    "model_metadata",
                    models.FileField(blank=True, null=True, upload_to="metadata"),
                ),
                (
                    "model_parameters",
                    models.FileField(blank=True, null=True, upload_to="parameters"),
                ),
                (
                    "finds",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="defcdb.finds",
                    ),
                ),
                (
                    "inclusion",
                    models.ManyToManyField(blank=True, to="threedmodels.inclusion"),
                ),
                (
                    "resource_metadata",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="threedmodels.project",
                    ),
                ),
            ],
        ),
    ]
