# Generated by Django 4.2.7 on 2023-11-07 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bib", "0001_initial"),
        ("defcdb", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageThesaurus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=500, null=True)),
                ("creator", models.CharField(blank=True, max_length=500, null=True)),
                ("image", models.FileField(blank=True, null=True, upload_to="images")),
                ("page", models.CharField(blank=True, max_length=100, null=True)),
                ("filename", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "literature",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bib.book",
                    ),
                ),
                (
                    "pottery_decoration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="defcdb.dc_finds_pottery_decoration",
                    ),
                ),
                (
                    "pottery_detail",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="defcdb.dc_finds_pottery_detail",
                    ),
                ),
                (
                    "pottery_form",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="defcdb.dc_finds_pottery_form",
                    ),
                ),
                ("region", models.ManyToManyField(blank=True, to="defcdb.dc_region")),
                (
                    "small_finds",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="defcdb.dc_finds_small_finds_type",
                    ),
                ),
            ],
        ),
    ]
